export const SET_PROFILE_WITHDATA = 'SET_PROFILE_WITHDATA';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';

export const LOG_OUT = 'LOG_OUT';
export const DELETE_AUTH_USER = 'DELETE_AUTH_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//post
export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const SINGLE_POST = 'SINGLE_POST';
export const NIGHT_MODE_ON = 'NIGHT_MODE_ON';
export const NIGHT_MODE_OFF = 'NIGHT_MODE_OFF';

export const REMOVE_LOADING = 'REMOVE_LOADING';
export const SET_LOADING = 'SET_LOADING';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER= 'UPDATE_USER';
export const UPDATE_OTHER_PROFILE= 'UPDATE_OTHER_PROFILE';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SEARCHED_USER = 'GET_SEARCHED_USER';
export const GET_ALL_COLLEGUES = 'GET_ALL_COLLEGUES';
export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const MY_GROUPS = 'MY_GROUPS';
export const HIDE_BIO = 'HIDE_BIO';
export const HIDE_SKILLS = 'HIDE_SKILLS';
export const SHOW_BIO = 'SHOW_BIO';
export const SHOW_SKILLS = 'SHOW_SKILLS';


export const MY_ACTIVE_GROUPS = 'MY_ACTIVE_GROUPS';
export const MY_FILTERED_GROUPS_FOR_POST = 'MY_FILTERED_GROUPS_FOR_POST';
export const MY_FILTERED_GROUPS_FOR_COLLEAGUES = 'MY_FILTERED_GROUPS_FOR_COLLEAGUES';





